Repository VisionariesAstu/EduBridge_Web, pull requests merged in 2024-07, with the labels that each got.

#34 1 init set up nextjs project with tailwind css
  .eslintrc.json
  .gitignore
  README.md
  next.config.mjs
  package.json
  pnpm-lock.yaml
  postcss.config.mjs
  public/next.svg
  public/vercel.svg
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  tailwind.config.ts
  tsconfig.json
Labels: good first issue

#41 chore: Add utility function for merging CSS classes
  components.json
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/app/layout.tsx
  src/components/UI/button.tsx
  src/lib/utils.ts
  src/styles/globals.css
  tailwind.config.ts
Labels: enhancement, init

#42 chore: Add utility function for merging CSS classes
  components.json
  package.json
  pnpm-lock.yaml
  public/Edu Bridge Logo White.png
  public/Edu Bridge Wide Logo White.png
  public/Hero_1.png
  public/texture.png
  src/app/auth/login/page.tsx
  src/app/auth/signup/page.tsx
  src/app/error.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/components/UI/card.tsx
  src/components/UI/custom_button.tsx
  src/components/UI/dropdown-menu.tsx
  src/components/UI/input.tsx
  src/components/UI/label.tsx
  src/components/UI/mode_toggle.tsx
  src/components/UI/select.tsx
  src/components/cutom_components.tsx
  src/components/form/form.tsx
  src/components/nav/landing_header.tsx
  src/components/theme_provider.tsx
  src/styles/fonts.ts
  src/styles/globals.css
Labels: duplicate

#44 9 feat create login page layout
  public/google_logo.png
  src/app/auth/login/page.tsx
  src/components/UI/input.tsx
Labels: feature, UI (Screen)

#47 [feat]: Add Verify Code page
  src/app/auth/verify/page.tsx
Labels: UI (Screen)

#48 11 feat create signup page layout
  src/app/auth/signup/page.tsx
  src/app/auth/signupinfo/countryLists.tsx
  src/app/auth/signupinfo/page.tsx
  src/components/UI/select.tsx
Labels: feature, UI (Screen)

#56 5 feat create header component for the landing page
  src/app/layout.tsx
  src/app/page.tsx
  src/app/page_1.tsx
  src/app/page_2.tsx
  src/app/page_3.tsx
  src/app/page_4.tsx
  src/components/details_card.tsx
  src/components/form/form.tsx
  src/components/landing_footer.tsx
  src/components/landing_header.tsx
  src/components/nav/landing_header.tsx
  src/components/theme_provider.tsx
  src/components/ui/custom_button.tsx
  src/styles/fonts.ts
Labels: duplicate, enhancement, UI (Screen)

#57 10 feat implement login form with validation
  package.json
  pnpm-lock.yaml
  src/app/auth/forgot/page.tsx
  src/app/auth/login/page.tsx
  src/app/auth/role/page.tsx
  src/app/auth/signup/page.tsx
  src/app/auth/signupinfo/page.tsx
  src/app/auth/verify/page.tsx
  src/app/layout.tsx
  src/app/teacher/layout.tsx
  src/components/buttons/login-submit.tsx
  src/components/form/login-form.tsx
  src/components/landing_footer.tsx
  src/components/ui/custom_button.tsx
  src/components/ui/form.tsx
  src/config/schemas.ts
  src/context/ctx.ts
  src/hooks/custom_hook.ts
  src/lib/prisma.ts
  src/server-actions/auth/login-action.ts
Labels: integration, enhancement, feature
